"use strict";
let name1 = document.getElementById('name');
let desig = document.getElementById('desig');
let phone = document.getElementById('phone');
let email = document.getElementById('email');
let add = document.getElementById('add');
let pass1 = document.getElementById('pass1');
let deg1 = document.getElementById('deg1');
let uni1 = document.getElementById('uni1');
let pass2 = document.getElementById('pass2');
let deg2 = document.getElementById('deg2');
let uni2 = document.getElementById('uni2');
let skill1 = document.getElementById('skill1');
let skill2 = document.getElementById('skill2');
let skill3 = document.getElementById('skill3');
let skill4 = document.getElementById('skill4');
let lang1 = document.getElementById('lang1');
let lang2 = document.getElementById('lang2');
let styear = document.getElementById('styear');
let endyear = document.getElementById('endyear');
let company = document.getElementById('company');
let jobtitle = document.getElementById('jobtitle');
let achiv1 = document.getElementById('achiv1');
let achiv2 = document.getElementById('achiv2');
let achiv3 = document.getElementById('achiv3');
let pic = document.getElementById('pic');
let subBtn = document.getElementById('subBtn');
let form = document.getElementById('form');
form?.addEventListener('submit', (e) => {
    e.preventDefault();
    localStorage.setItem('name', name1.value);
    localStorage.setItem('desig', desig.value);
    localStorage.setItem('phone', phone.value);
    localStorage.setItem('email', email.value);
    localStorage.setItem('add', add.value);
    localStorage.setItem('pass1', pass1.value);
    localStorage.setItem('deg1', deg1.value);
    localStorage.setItem('uni1', uni1.value);
    localStorage.setItem('pass2', pass2.value);
    localStorage.setItem('deg2', deg2.value);
    localStorage.setItem('uni2', uni2.value);
    localStorage.setItem('skill1', skill1.value);
    localStorage.setItem('skill2', skill2.value);
    localStorage.setItem('skill3', skill3.value);
    localStorage.setItem('skill4', skill4.value);
    localStorage.setItem('lang1', lang1.value);
    localStorage.setItem('lang2', lang2.value);
    localStorage.setItem('styear', styear.value);
    localStorage.setItem('endyear', endyear.value);
    localStorage.setItem('company', company.value);
    localStorage.setItem('jobtitle', jobtitle.value);
    localStorage.setItem('achiv1', achiv1.value);
    localStorage.setItem('achiv2', achiv2.value);
    localStorage.setItem('achiv3', achiv3.value);
    if (pic.files && pic.files[0]) {
        let reader = new FileReader();
        reader.readAsDataURL(pic.files[0]);
        reader.addEventListener('load', () => {
            let imageToText = reader.result;
            localStorage.setItem('pic', imageToText);
        });
    }
    window.location.href = "./resume/resume.html";
});
